subroutine ncwrite
    use varmod
    use netcdf
    !NC FILE OUT=====================================================================
print*, odir
status = nf90_create(odir,nf90_clobber,ncid);             call chkerr(status,'writing file')

status = nf90_def_dim(ncid,nam_tim,nt,dim_tim);              call chkerr(status,'dimensioning')
status = nf90_def_dim(ncid,nam_hgt,nh,dim_hgt);              call chkerr(status,'dimensioning')
status = nf90_put_att(ncid,vid_tims,att_unt,unt_tim);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_hgts,att_unt,unt_hgt);      call chkerr(status,'unit')
dims=(/dim_tim,dim_hgt/)
status = nf90_def_var(ncid,nam_bsc,nf90_float,dims,vid_bsc);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_tim,nf90_float,dim_tim,vid_tim);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_hgt,nf90_float,dim_hgt,vid_hgt);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_cbh1,nf90_float,dim_tim,vid_cbh1);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_cbh2,nf90_float,dim_tim,vid_cbh2);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_cbh3,nf90_float,dim_tim,vid_cbh3);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_vviso,nf90_float,dim_tim,vid_vviso);   call chkerr(status,'defining')

status = nf90_def_var(ncid,nam_scale,nf90_float,dim_tim,vid_scalefo);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_hres,nf90_float,dim_tim,vid_hreso);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_hlen,nf90_float,dim_tim,vid_hleno);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_Leng,nf90_float,dim_tim,vid_Lengo);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_temp,nf90_float,dim_tim,vid_Ltempo);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_Wtrans,nf90_float,dim_tim,vid_Wtranso);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_Tangle,nf90_float,dim_tim,vid_Tangleo);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_Blit,nf90_float,dim_tim,vid_Blito);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_Ptype,nf90_float,dim_tim,vid_Ptypeo);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_Gtype,nf90_float,dim_tim,vid_Gtypeo);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_Btype,nf90_float,dim_tim,vid_Btypeo);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sampr,nf90_float,dim_tim,vid_sampro);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sumb,nf90_float,dim_tim,vid_sumbo);   call chkerr(status,'defining')

status = nf90_def_var(ncid,nam_alm01,nf90_float,dim_tim,vid_alm01);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm02,nf90_float,dim_tim,vid_alm02);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm03,nf90_float,dim_tim,vid_alm03);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm04,nf90_float,dim_tim,vid_alm04);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm06,nf90_float,dim_tim,vid_alm06);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm07,nf90_float,dim_tim,vid_alm07);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm08,nf90_float,dim_tim,vid_alm08);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm15,nf90_float,dim_tim,vid_alm15);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_alm16,nf90_float,dim_tim,vid_alm16);   call chkerr(status,'defining')

status = nf90_def_var(ncid,nam_wrn01,nf90_float,dim_tim,vid_wrn01);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn02,nf90_float,dim_tim,vid_wrn02);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn03,nf90_float,dim_tim,vid_wrn03);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn04,nf90_float,dim_tim,vid_wrn04);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn06,nf90_float,dim_tim,vid_wrn06);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn08,nf90_float,dim_tim,vid_wrn08);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn09,nf90_float,dim_tim,vid_wrn09);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn10,nf90_float,dim_tim,vid_wrn10);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn11,nf90_float,dim_tim,vid_wrn11);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn12,nf90_float,dim_tim,vid_wrn12);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn13,nf90_float,dim_tim,vid_wrn13);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn14,nf90_float,dim_tim,vid_wrn14);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wrn15,nf90_float,dim_tim,vid_wrn15);   call chkerr(status,'defining')

status = nf90_def_var(ncid,nam_sta01,nf90_float,dim_tim,vid_sta01);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta02,nf90_float,dim_tim,vid_sta02);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta03,nf90_float,dim_tim,vid_sta03);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta04,nf90_float,dim_tim,vid_sta04);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta05,nf90_float,dim_tim,vid_sta05);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta06,nf90_float,dim_tim,vid_sta06);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta07,nf90_float,dim_tim,vid_sta07);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta09,nf90_float,dim_tim,vid_sta09);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta10,nf90_float,dim_tim,vid_sta10);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sta11,nf90_float,dim_tim,vid_sta11);   call chkerr(status,'defining')

status = nf90_put_att(ncid,vid_tim,att_unt,unt_tim);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_hgt,att_unt,unt_hgt);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_cbh1,att_unt,unt_hgt);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_cbh2,att_unt,unt_hgt);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_cbh3,att_unt,unt_hgt);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_vviso,att_unt,unt_hgt);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_cbh1,'_FillValue',fv);      call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbh2,'_FillValue',fv);      call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbh3,'_FillValue',fv);      call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_vviso,'_FillValue',fv);      call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bsc,att_unt,unt_bsc);      call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_bsc,'_FillValue',fv);      call chkerr(status,'Fillvalue')

status = nf90_put_att(ncid,vid_scalefo,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_hreso,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_hleno,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Lengo,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Ltempo,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Wtranso,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Tangleo,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Blito,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Ptypeo,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Gtypeo,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_Btypeo,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_sampro,'_Fillvalue',fv);   call chkerr(status,'defining')
status = nf90_put_att(ncid,vid_sumbo,'_Fillvalue',fv);   call chkerr(status,'defining')

status = nf90_put_att(ncid,vid_alm01,'description',att_alm01);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm02,'description',att_alm02);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm03,'description',att_alm03);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm04,'description',att_alm04);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm06,'description',att_alm06);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm07,'description',att_alm07);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm08,'description',att_alm08);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm15,'description',att_alm15);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_alm16,'description',att_alm16);   call chkerr(status,'descriptions')

status = nf90_put_att(ncid,vid_wrn01,'description',att_wrn01);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn02,'description',att_wrn02);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn03,'description',att_wrn03);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn04,'description',att_wrn04);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn06,'description',att_wrn06);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn08,'description',att_wrn08);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn09,'description',att_wrn09);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn10,'description',att_wrn10);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn11,'description',att_wrn11);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn12,'description',att_wrn12);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn13,'description',att_wrn13);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn14,'description',att_wrn14);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_wrn15,'description',att_wrn15);   call chkerr(status,'descriptions')

status = nf90_put_att(ncid,vid_sta01,'description',att_sta01);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta02,'description',att_sta02);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta03,'description',att_sta03);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta04,'description',att_sta04);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta05,'description',att_sta05);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta06,'description',att_sta06);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta07,'description',att_sta07);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta09,'description',att_sta09);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta10,'description',att_sta10);   call chkerr(status,'descriptions')
status = nf90_put_att(ncid,vid_sta11,'description',att_sta11);   call chkerr(status,'descriptions')

status = nf90_enddef(ncid)
status = nf90_put_var(ncid,vid_tim,t);                    call chkerr(status,'t in')
status = nf90_put_var(ncid,vid_hgt,h);                    call chkerr(status,'h in')
status = nf90_put_var(ncid,vid_bsc,bscd);                              call chkerr(status,'bsc in')
status = nf90_put_var(ncid,vid_cbh1,cbh1o);                    call chkerr(status,'cbh1 in')
status = nf90_put_var(ncid,vid_cbh2,cbh2o);                    call chkerr(status,'cbh2 in')
status = nf90_put_var(ncid,vid_cbh3,cbh3o);                    call chkerr(status,'cbh3 in')
status = nf90_put_var(ncid,vid_cbh3,vviso);                    call chkerr(status,'vvis in')

status = nf90_put_var(ncid,vid_scalefo,scalefo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_hreso,hreso);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_hleno,hlengo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Lengo,Lengo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Ltempo,Ltempo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Wtranso,Wtranso);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Tangleo,Tangleo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Blito,Blito);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Ptypeo,Ptypeo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Gtypeo,Gtypeo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_Btypeo,Btypeo);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_sampro,sampro);   call chkerr(status,'defining')
status = nf90_put_var(ncid,vid_sumbo,sumbo);   call chkerr(status,'defining')

status = nf90_put_var(ncid,vid_alm01,alarm_flag(:,1));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm02,alarm_flag(:,2));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm03,alarm_flag(:,3));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm04,alarm_flag(:,4));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm06,alarm_flag(:,6));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm07,alarm_flag(:,7));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm08,alarm_flag(:,8));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm15,alarm_flag(:,15));          call chkerr(status,'alm in')
status = nf90_put_var(ncid,vid_alm16,alarm_flag(:,16));          call chkerr(status,'alm in')

status = nf90_put_var(ncid,vid_wrn01,warning_flag(:,1));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn02,warning_flag(:,2));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn03,warning_flag(:,3));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn04,warning_flag(:,4));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn06,warning_flag(:,6));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn08,warning_flag(:,8));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn09,warning_flag(:,9));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn10,warning_flag(:,10));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn11,warning_flag(:,11));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn12,warning_flag(:,12));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn13,warning_flag(:,13));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn14,warning_flag(:,14));          call chkerr(status,'wrn in')
status = nf90_put_var(ncid,vid_wrn15,warning_flag(:,15));          call chkerr(status,'wrn in')

status = nf90_put_var(ncid,vid_sta01,status_flag(:,1));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta02,status_flag(:,2));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta03,status_flag(:,3));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta04,status_flag(:,4));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta05,status_flag(:,5));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta06,status_flag(:,6));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta07,status_flag(:,7));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta09,status_flag(:,9));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta10,status_flag(:,10));          call chkerr(status,'sta in')
status = nf90_put_var(ncid,vid_sta11,status_flag(:,11));          call chkerr(status,'sta in')

status = nf90_close(ncid);                                call chkerr(status,'end')



status = nf90_create(odir2,nf90_clobber,ncid);             call chkerr(status,'writing file')

status = nf90_def_dim(ncid,nam_tims,nts,dim_tims);           call chkerr(status,'dimensioning')
status = nf90_def_dim(ncid,nam_hgts,nhs,dim_hgts);           call chkerr(status,'dimensioning')
dimss=(/dim_tims,dim_hgts/)
status = nf90_def_var(ncid,nam_tims,nf90_float,dim_tims,vid_tims);     call chkerr(status,'01defining')
status = nf90_def_var(ncid,nam_hgts,nf90_float,dim_hgts,vid_hgts);     call chkerr(status,'02defining')
status = nf90_def_var(ncid,nam_cbct,nf90_float,dim_tims,vid_cbct);     call chkerr(status,'03defining')
status = nf90_def_var(ncid,nam_cbcv1,nf90_float,dim_tims,vid_cbcv1);   call chkerr(status,'04defining')
status = nf90_def_var(ncid,nam_cbcv2,nf90_float,dim_tims,vid_cbcv2);   call chkerr(status,'05defining')
status = nf90_def_var(ncid,nam_cbcv3,nf90_float,dim_tims,vid_cbcv3);   call chkerr(status,'06defining')
status = nf90_def_var(ncid,nam_bhct,nf90_float,dim_tims,vid_bhct);     call chkerr(status,'07defining')
status = nf90_def_var(ncid,nam_bhcv1,nf90_float,dim_tims,vid_bhcv1);   call chkerr(status,'08defining')
status = nf90_def_var(ncid,nam_bhcv2,nf90_float,dim_tims,vid_bhcv2);   call chkerr(status,'09defining')
status = nf90_def_var(ncid,nam_bhcv3,nf90_float,dim_tims,vid_bhcv3);   call chkerr(status,'10defining')
status = nf90_def_var(ncid,nam_bicv1,nf90_float,dim_tims,vid_bicv1);   call chkerr(status,'11defining')
status = nf90_def_var(ncid,nam_bicv2,nf90_float,dim_tims,vid_bicv2);   call chkerr(status,'12defining')
status = nf90_def_var(ncid,nam_bicv3,nf90_float,dim_tims,vid_bicv3);   call chkerr(status,'13defining')
status = nf90_def_var(ncid,nam_cbh1s,nf90_float,dim_tims,vid_cbh1s);   call chkerr(status,'14defining')
status = nf90_def_var(ncid,nam_cbh2s,nf90_float,dim_tims,vid_cbh2s);   call chkerr(status,'15defining')
status = nf90_def_var(ncid,nam_cbh3s,nf90_float,dim_tims,vid_cbh3s);   call chkerr(status,'16defining')
status = nf90_def_var(ncid,nam_blh1s,nf90_float,dim_tims,vid_blh1s);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_blh2s,nf90_float,dim_tims,vid_blh2s);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_blh3s,nf90_float,dim_tims,vid_blh3s);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_bli1s,nf90_float,dim_tims,vid_bli1s);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_bli2s,nf90_float,dim_tims,vid_bli2s);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_bli3s,nf90_float,dim_tims,vid_bli3s);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_qcflag,nf90_float,dim_tims,vid_qcflag);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_wflag,nf90_float,dim_tims,vid_wflag);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_aflag,nf90_float,dim_tims,vid_aflag);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_vvis,nf90_float,dim_tims,vid_vvis);   call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_bscs,nf90_float,dimss,vid_bscs);        call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_bsct,nf90_float,dimss,vid_bsct);        call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_bscv,nf90_float,dimss,vid_bscv);        call chkerr(status,'defining')
status = nf90_def_var(ncid,nam_sumb,nf90_float,dim_tim,vid_sumb);   call chkerr(status,'defining')

status = nf90_put_att(ncid,vid_qcflag,'description','0 means no warning or alarm');                call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbct,'_FillValue',fv);                  call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbcv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbcv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbcv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bhct,'_FillValue',fv);                  call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bhcv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bhcv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bhcv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bicv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bicv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bicv1,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_vvis,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_qcflag,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_aflag,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_aflag,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_sumb,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbh1s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_cbh2s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_cbh3s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_cbh1s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbh2s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_cbh3s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_blh1s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_blh2s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_blh3s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_blh1s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_blh2s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_blh3s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bli1s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_bli2s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_bli3s,att_unt,unt_hgt);                 call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_bli1s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bli2s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bli3s,'_FillValue',fv);                 call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bscs,att_unt,unt_bsc);                  call chkerr(status,'unit')
status = nf90_put_att(ncid,vid_bscs,'_FillValue',fv);                  call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bsct,'_FillValue',fv);                  call chkerr(status,'Fillvalue')
status = nf90_put_att(ncid,vid_bscv,'_FillValue',fv);                  call chkerr(status,'Fillvalue')
status = nf90_enddef(ncid)
status = nf90_put_var(ncid,vid_cbct,count_cbh);                        call chkerr(status,'cbct3s in')
status = nf90_put_var(ncid,vid_cbcv1,valid_cbh1);                      call chkerr(status,'cbcv11s in')
status = nf90_put_var(ncid,vid_cbcv2,valid_cbh2);                      call chkerr(status,'cbcv12s in')
status = nf90_put_var(ncid,vid_cbcv3,valid_cbh3);                      call chkerr(status,'cbct3s in')
status = nf90_put_var(ncid,vid_bhct,count_blh);                        call chkerr(status,'bhct3s in')
status = nf90_put_var(ncid,vid_bhcv1,valid_blh1);                      call chkerr(status,'bhcv11s in')
status = nf90_put_var(ncid,vid_bhcv2,valid_blh2);                      call chkerr(status,'bhcv12s in')
status = nf90_put_var(ncid,vid_bhcv3,valid_blh3);                      call chkerr(status,'bhct3s in')
status = nf90_put_var(ncid,vid_bicv1,valid_bli1);                      call chkerr(status,'bicv11s in')
status = nf90_put_var(ncid,vid_bicv2,valid_bli2);                      call chkerr(status,'bicv12s in')
status = nf90_put_var(ncid,vid_bicv3,valid_bli3);                      call chkerr(status,'bict3s in')
status = nf90_put_var(ncid,vid_vvis,vvis);                      call chkerr(status,'bict3s in')
status = nf90_put_var(ncid,vid_qcflag,QCflags);                      call chkerr(status,'bict3s in')
status = nf90_put_var(ncid,vid_wflag,wflags);                      call chkerr(status,'bict3s in')
status = nf90_put_var(ncid,vid_aflag,aflags);                      call chkerr(status,'bict3s in')
status = nf90_put_var(ncid,vid_sumb,sumb);                      call chkerr(status,'bict3s in')
status = nf90_put_var(ncid,vid_cbh1s,cbh1);                            call chkerr(status,'cbh1s in')
status = nf90_put_var(ncid,vid_cbh2s,cbh2);                            call chkerr(status,'cbh2s in')
status = nf90_put_var(ncid,vid_cbh3s,cbh3);                            call chkerr(status,'cbh3s in')
status = nf90_put_var(ncid,vid_blh1s,blh1);                            call chkerr(status,'blh1s in')
status = nf90_put_var(ncid,vid_blh2s,blh2);                            call chkerr(status,'blh2s in')
status = nf90_put_var(ncid,vid_blh3s,blh3);                            call chkerr(status,'blh3s in')
status = nf90_put_var(ncid,vid_bli1s,bli1);                            call chkerr(status,'bli1s in')
status = nf90_put_var(ncid,vid_bli2s,bli2);                            call chkerr(status,'bli2s in')
status = nf90_put_var(ncid,vid_bli3s,bli3);                            call chkerr(status,'bli3s in')
status = nf90_put_var(ncid,vid_tims,ts);                               call chkerr(status,'t in')
status = nf90_put_var(ncid,vid_hgts,hs);                               call chkerr(status,'h in')
status = nf90_put_var(ncid,vid_bscs,bscs);                             call chkerr(status,'bsc in')
status = nf90_put_var(ncid,vid_bsct,count_bsc);                        call chkerr(status,'bsct in')
status = nf90_put_var(ncid,vid_bscv,valid_bsc);                        call chkerr(status,'bscv in')
status = nf90_close(ncid);                                             call chkerr(status,'end')

end subroutine ncwrite
subroutine chkerr(status,msg)
use netcdf
implicit none
integer,intent(in)::status
character(*)::msg
if(status.eq.nf90_noerr)then
        print*,'stage: ',msg,'  NetCDF F90 library message: ',NF90_STRERROR(status),'success'
else
        print*,'stage: ',msg,'  NetCDF F90 library message: ',NF90_STRERROR(status)
        stop 'stop'
endif
endsubroutine
